[package]
name = "rustboy"
version = "0.1.0"
edition = "2024"

[lints.rust]
dead_code = "allow"
unused_variables = "allow"

[features]
default = []
trace_memory = []
with_sdl = ["sdl2"]

[dependencies]
sdl2 = { version = "0.37", optional = true }
